theme: jekyll-theme-dinky
title: Breaking back into the coding world after a loooong hiatus
description: Currently working as a Data Analyst but looking for freelance web design and programming projects. #Havefungetpaid
